apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oap
    choerodon.io/infra: skywalking-oap
    choerodon.io/logs-parser: docker
    choerodon.io/release: skywalking-oap
  name: skywalking-oap
  namespace: skywalking-min
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: oap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oap
        choerodon.io/infra: skywalking-oap
        choerodon.io/release: skywalking-oap
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xms1024M -Xmx1024M
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        #image: registry.cn-shanghai.aliyuncs.com/vinkdong/skywalking-oap:v6.0.0-beta
        image: apache/skywalking-oap-server:6.2.0
        imagePullPolicy: IfNotPresent
        name: oap
        ports:
        - containerPort: 11800
          name: grpc
          protocol: TCP
        - containerPort: 12800
          name: rest
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /apache-skywalking-apm-incubating/config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: skywalking-oap
      serviceAccountName: skywalking-oap
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: oap-config
        name: config
