apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-metrics-storage-mysql-promethues 
  namespace: monitor
spec:
  mountOptions:
    - vers=4.0
    #noresvport设置为非保密端口
    - noresvport
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "metrics-storage-mysql-promethues"
  #表示使用本地存储
  local:
    path: /datavip/k8s-data/pv-metrics-storage-mysql-promethues
  #使用local pv时必须定义nodeAffinity，Kubernetes Scheduler需要使用PV的nodeAffinity描述信息来保证Pod能够调度到有对应local volume的Node上。
  #创建local PV之前，你需要先保证有对应的storageClass已经创建。
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          #future是pod需要分不到的主机名，这台主机上开启了local-pv资源。
          - future
  #生产环境使用云存储
  #nfs:
  #  server: 你的存储地址
  #  path: /pv-metrics-storage-mysql-promethues
