apiVersion: v1
kind: Service
metadata:
  name: prometheus-mq-rocketmq
  namespace: monitor
  labels:
    app: prometheus-mq-rocketmq
spec:
  ports:
  - port: 9090
    name: prom-graph
  type: NodePort
  selector:
    app: prometheus-mq-rocketmq
