apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: es-c1-skywalking
  name: es-c1-skywalking
  namespace: biz
spec:
  rules:
  - host: es-c1-skywalking-admin
    http:
      paths:
      - backend:
          serviceName: elasticsearch-master
          servicePort: 9200
        path: /
  - host: es-c1-skywalking
    http:
      paths:
      - backend:
          serviceName: elasticsearch-master
          servicePort: 9300
        path: /
